### PR TITLE
fix multiple issues; closes #116 #151 #153 #154 #166 #203

### LINKED ISSUE #116: Dark level overlay isn't centered on party icon
Image

### PR DESCRIPTION
**Pull request by fuzziqersoftware**
Most commits included here are confined to a single file each and (I hope) are relatively self-explanatory, but I will split this up if requested.

### CODE REVIEW

File: src/realmz_orig/centerpict.c [hunk 1]
```diff
@@ -280,15 +245,63 @@ void centerpict(void) {
...
+    /* *** CHANGED FROM ORIGINAL IMPLEMENTATION ***
+     * NOTE(fuzziqersoftware): The original logic was hard to follow and centered the darkness mask in the wrong place
+     * after the expansion to 800x600, so I've rewritten it.
+     */
+
+    // The upper-left corner of the party icon should be at the center of the darkness mask. That is, the origin of the
+    // rect that we're going to pass to CopyMask should be 160 pixels left and above the party's tile's origin. The
+    // darkness mask is 320x320, so the rect's size is always the same. In the original logic, the darkness mask was
+    // stretched if the screen size is 800x600, but we don't do that - we always reveal the same amount of the
+    // playfield, regardless of the window/screen size.
```
Comment (danapplegate) [inline src/realmz_orig/centerpict.c]: Ah, nice catch. I wouldn't have thought of this!
